name: ermokids
description: App infantil educativo
publish_to: "none"

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^6.0.0

flutter:
  uses-material-design: true

  flutter:
  assets:
    - assets/images/
    - assets/music/
    - assets/puzzles/
